-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 20:30:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Autobuses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Autobuses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Autobuses` DEFAULT CHARACTER SET utf8 ;
USE `Autobuses` ;

-- -----------------------------------------------------
-- Table `Autobuses`.`AUTOBUSES`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Autobuses`.`AUTOBUSES` (
  `NO_AUTOBUS` INT NOT NULL,
  `MARCA` VARCHAR(45) NOT NULL,
  `TIPO` VARCHAR(45) NOT NULL,
  `PLAZAS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NO_AUTOBUS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autobuses`.`FACULTAD`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Autobuses`.`FACULTAD` (
  `ID_FACULTAD` INT NOT NULL,
  `NOM_FACULTAD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_FACULTAD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autobuses`.`RESPONSABLE`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Autobuses`.`RESPONSABLE` (
  `CVE_PERSONA` INT NOT NULL,
  `NOM_PERSONA` VARCHAR(45) NOT NULL,
  `APE_PERSONA` VARCHAR(45) NOT NULL,
  `ID_FACULTAD` INT NOT NULL,
  PRIMARY KEY (`CVE_PERSONA`),
  CONSTRAINT `fk_RESPONSABLE_FACULTAD1`
    FOREIGN KEY (`ID_FACULTAD`)
    REFERENCES `Autobuses`.`FACULTAD` (`ID_FACULTAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autobuses`.`PRESTAMO`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Autobuses`.`PRESTAMO` (
  `NO_AUTOBUS` INT NOT NULL,
  `F_PRESTAMO` DATE NOT NULL,
  `F_INICIO` DATE NOT NULL,
  `HORA_INICIO` TIME NOT NULL,
  `F_FIN` DATE NOT NULL,
  `HORA_FIN` TIME NOT NULL,
  `ORIGEN` VARCHAR(45) NOT NULL,
  `DESTINO` VARCHAR(45) NOT NULL,
  `CVE_PERSONA` INT NOT NULL,
  CONSTRAINT `fk_PRESTAMO_AUTOBUSES`
    FOREIGN KEY (`NO_AUTOBUS`)
    REFERENCES `Autobuses`.`AUTOBUSES` (`NO_AUTOBUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRESTAMO_RESPONSABLE1`
    FOREIGN KEY (`CVE_PERSONA`)
    REFERENCES `Autobuses`.`RESPONSABLE` (`CVE_PERSONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
